### ISSUE TITLE
Change Modules

### ISSUE THREAD

**Issue by Alexsen56** [rupin/PiZeroMagicMirror#6]
Once I have this up and running, how can I make changes to the modules?

**Comment by rupin** [comment]
It depends what you want to change. 

The UI uses 960gs for css layouts, jQuery for javascript interactions, and Python for the scripts. 

Depending on what you wish to change, you can start off experimenting until you reach your desired outcome. 

I haven't made it as modular as I think it should be, because it was for a one-off student project. 

I don't have plans to start making it modular now.
