### ISSUE TITLE
Not working on latest Pi OS

### ISSUE THREAD

**Issue by chrwei** [rupin/PiZeroMagicMirror#7]
Using a pizeroW and debian bookworm based PiOS I only get a black screen after startx, no matter what URL I use.  I can see midori running though, just nothing ever shows up on screen.

using the "Legacy" bullseye based PiOS loads pages as expected.

**Comment by rupin** [comment]
I would change the URL being loaded into the browser to say google.com and try to see if that starts. If it does, then the website is where I would start with. 

Try loading the URL on a computer if it is being served on the same LAN.

**Comment by chrwei** [comment]
i did, url doesn't matter, it never even gets the white midori screen, or the URL bar showing it's loading

**Comment by rupin** [comment]
These are potential things which you can check, i would think about solving it this way. 
1) you can get away from the console, and try loading the rpi screen using VNC server. 
2) Are you able to load midori using the desktop? If not, what errors does it give? 
3) Is there a different browser that you can load on debian in kiosk mode instead of midori?

**Comment by chrwei** [comment]
isn't the whole point of this project to run midori on a pi-zero without a regular desktop install?  is there another browser that would work?  desktop+browser on a pizero is painful no matter what OS version, I'm not going there.

if the answer is that we just can't do this on bookworm due to the it needing more resources than the zero has, that's fine, but the readme should say so.  bookworm takes double the disk space too, 8GB sd card minimum when bullseye does fine on 4GB

**Comment by rupin** [comment]
The whole point of the project is to run a browser in kiosk mode, loads a website from somewhere,  so that it eventually shows up on a screen. If you had to debug issues, it would be helpful to load the browser on the desktop just for the purposes of figuring out why it doesnt work. 

The last update for the repo was in 2022, and the project installation is running fine till date. Updates have been stopped, because i dont intend to fix anything which is not broken.

**Comment by chrwei** [comment]
understood, and on bullseye it's not broken, but bookworm it is.  I'm happy with that, but knowing it going in would have saved a lot of time
